### ISSUE TITLE
Can't do anything

### ISSUE THREAD

**Issue by GatoSoft-Software** [WKS410/animeonegai-downloader-nx#2]
The only command that works is for help (-h). Otherwise, I get similar errors to this:

```
=== AnimeOnegai Downloader NX 1.0.4 ===

Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AO.py", line 477, in <module>
    main()
  File "AO.py", line 54, in main
    json_login = login_api.json()
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[19920] Failed to execute script 'AO' due to unhandled exception!
```

**Comment by jcdark** [comment]
This project appears to be fake
